---
title: "Demographics vs Imaging Audit"
output: html_notebook
---

## What are we missing?

```{r}
library(tidyverse)
library(here)
```

Grab all the demographics:

```{r}
#all the demographic data we've processed
demographics_all <- list.files(here("outputs"), pattern = ".rds", full.names = TRUE) %>%
  map_df(readRDS) %>%
  mutate(across(c(study, study_site, wave, education), ~as.factor(.)))
```

Filter by the participants we have in our final production dataset:

```{r}
# all the imaging datasets we have
get_subjects <- function(x){
  
  list.dirs(x, recursive=FALSE, full.names = FALSE) %>%
    tibble(source=x, participant_id=.) %>%
    filter(str_detect(participant_id, "sub-")) %>%
    return()
}

datasets <- list.dirs("/cbica/projects/RBC/RBC_RAWDATA/bidsdatasets", recursive = FALSE)
imaging_all <- map_df(datasets, get_subjects) %>%
  mutate(study = str_extract(source, "(?<=bidsdatasets\\/).+"))

imaging_all <- get_subjects("/cbica/projects/RBC/RBC_RAWDATA/bidsdatasets/ECAS/BIDS") %>%
  mutate(study = str_extract(source, "(?<=bidsdatasets\\/).+(?=\\/)")) %>%
  bind_rows(imaging_all) %>%
  mutate(study = case_when(
    study == "HRC"   ~ "BHRC",
    study == "ECAS"  ~ "PACCT",
    study == "CCNP"  ~ "Colornest",
    TRUE             ~ study
  ))
  
```

Imaging but no demographics at all:

```{r}
imaging_w_demo <- imaging_all %>%
  left_join(demographics_all)

missing_demo <- imaging_all %>%
  left_join(demographics_all) %>%
  filter(if_all(!c(source, participant_id, study), is.na))

missing_demo %>%
  group_by(study) %>%
  summarise(n=n())
```

```{r}
imaging_w_demo %>%
 group_by(study) %>%
 summarise(n=n())
```


```{r}
imaging_all %>%
 left_join(demographics_all) %>%
 select(!c(participant_id, source, study_site, wave)) %>%
 gg_miss_var(facet=study, show_pct = TRUE)
```






